language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.4.12
  - DJANGO=Django==1.5.7
  - DJANGO=Django==1.6.4
  - DJANGO=Django==1.7.5
  - DJANGO=Django==1.8.2

install:
  - pip install $DJANGO
  - pip install coverage coveralls
  - pip install numpy>=1.6.1
  - pip install django-model-utils >=1.4.0
  - pip install pandas>=0.12.0

script:
  - coverage run -a setup.py test
  - coverage report
matrix:
  exclude:
   - python: 2.6
     env: DJANGO=Django==1.7.5
     env: DJANGO=Django==1.8.2
   - python: 3.2
     env: DJANGO=Django==1.4.12
   - python: 3.3
     env: DJANGO=Django==1.4.12
   - python: 3.4
     env: DJANGO=Django==1.4.12
after_success: coveralls
